### ISSUE TITLE
Incorporate the Google Map API key into the APK

### ISSUE THREAD

**Issue by MPepito** [PocketTutor-Team/pockettutor-app#105]

**Comment by LeaBlancher** [comment]
This is solved. The problem was that the MAPS_API_KEY we had uploaded to Github secret contains only the key and not the MAPS_API_KEY="key". So when the CI retrieved it and saved it into the local.properties file, the name field was missing and so it was not recognized as the map key by our build.gradle.kts. I updated the Github secret with the correct value and it fixes the issue.
